In [9]:
import numpy as np
import blobfile as bf
from PIL import Image

path = './output/train/0.jpg.png'
with bf.BlobFile(path, "rb") as f:
    pil_image = Image.open(f)
    pil_image.load()
pil_image = np.array(pil_image.convert("RGB"))
print(pil_image)
print(np.allclose(pil_image[..., [0]], pil_image[..., [1]]))
print(np.allclose(pil_image[..., [1]], pil_image[..., [2]]))
print(pil_image.shape)
print(np.min(pil_image))
print(np.max(pil_image))

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
True
True
(256, 256, 3)
0
255


In [15]:
# import os
# os.rename('./out.jpg.png', './out.png')
import glob, os
path = '/data/mint/DPM_Dataset/ffhq_256_with_anno/shadow_masks/train/'
for f in glob.glob('/data/mint/DPM_Dataset/ffhq_256_with_anno/shadow_masks/train/*.png'):
    name = f.split('/')[-1].split('.jpg')
    name = ''.join(name)
    new_f = path+name
    os.rename(f, new_f)

In [ ]:
# import os
# os.rename('./out.jpg.png', './out.png')
import glob, os
path = '/data/mint/DPM_Dataset/ffhq_256_with_anno/shadow_masks/valid/'
for f in glob.glob('/data/mint/DPM_Dataset/ffhq_256_with_anno/shadow_masks/valid/*.png'):
    if '.jpg.png' not in f: assert False
    name = f.split('/')[-1].split('.jpg')
    name = ''.join(name)
    new_f = path+name
    os.rename(f, new_f)